package suggestapi

import "blinders/packages/logging"

var DefaultLanguageUnit = []logging.SuggestPracticeUnitResponse{
	{
		Word:        "Entrepreneur",
		Explain:     "An individual who organizes and operates a business or businesses, taking on greater than normal financial risks in order to do so.",
		ExpandWords: []string{"innovator", "founder", "businessperson", "visionary"},
	},
	{
		Word:        "Venture Capital",
		Explain:     "Funding provided by investors to startup companies and small businesses that are perceived to have long-term growth potential.",
		ExpandWords: []string{"investment", "funding", "capital", "seed money"},
	},
	{
		Word:        "Pitch Deck",
		Explain:     "A presentation created by entrepreneurs that provides an overview of their business, often used to seek funding from investors.",
		ExpandWords: []string{"presentation", "slide deck", "investment pitch", "startup pitch"},
	},
	{
		Word:        "Bootstrapping",
		Explain:     "Building a company from the ground up with little or no outside capital, relying on personal savings and revenue generated by the business.",
		ExpandWords: []string{"self-funding", "DIY funding", "self-sustaining", "frugal entrepreneurship"},
	},
	{
		Word:        "MVP (Minimum Viable Product)",
		Explain:     "The simplest version of a product that can be released to market, allowing a team to collect the maximum amount of validated learning about customers with the least effort.",
		ExpandWords: []string{"prototype", "early version", "beta product", "test product"},
	},
	{
		Word:        "Disruption",
		Explain:     "The process by which a new product or service creates a significant impact on an existing market, often displacing established businesses or practices.",
		ExpandWords: []string{"innovation", "game changer", "market revolution", "industry shake-up"},
	},
	{
		Word:        "Pivot",
		Explain:     "A fundamental change in a startup's business model, product, or strategy, usually undertaken in response to market feedback or changing circumstances.",
		ExpandWords: []string{"course correction", "strategic shift", "business model adjustment", "adaptive change"},
	},
	{
		Word:        "Acquisition",
		Explain:     "The process by which one company purchases a significant portion of or all of another company's shares to gain control of its assets, technologies, or talent.",
		ExpandWords: []string{"takeover", "merger", "buyout", "consolidation"},
	},
	{
		Word:        "Incubator",
		Explain:     "A program designed to help startups grow and succeed by providing resources such as office space, mentoring, and networking opportunities.",
		ExpandWords: []string{"accelerator", "startup hub", "innovation center", "launchpad"},
	},
	{
		Word:        "Scale-Up",
		Explain:     "The phase in a startup's lifecycle when it experiences rapid growth in revenue, customer base, and workforce, often requiring significant expansion of operations and resources.",
		ExpandWords: []string{"growth stage", "expansion phase", "scaling", "ramp-up"},
	},
}
