name: Go CI
on:
  push:
    branches: [main, dev]
  pull_request:
jobs:
  main:
    name: Lint and Test
    environment: development
    runs-on: ubuntu-20.04
    services:
      mongo:
        image: mongo:latest
        options: >-
          --health-cmd mongosh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
              
      - name: Lint by golangci-lint  
        run: go list -f '{{.Dir}}/...' -m | xargs -n 1 sh -c 'golangci-lint run $0 || exit -1'

      # - name: Test 
      #   run: go list -f '{{.Dir}}/...' -m | xargs -n 1 sh -c 'go test $0 || exit -1'
